[naverpost]
title = "네이버 포스트 ─ YG FAMILY "
url = "https://m.post.naver.com/my.naver?memberNo=37292560"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"
onFail = "stale"

[navertv]
title = "네이버 TV ─ YG FAMILY"
url = "https://tv.naver.com/ygfamily/clips"
entrySelector = "div[class^='cds _MM_CARD']"
titleSelector = "dt.title"
linkSelector = "dt.title a"
imageSelector = "div.cds_type a img"
contentSelector = "span.tm_b"
waitUntil = "networkidle"
onFail = "stale"